name: Release PolarPaper
on:
  push:
    branches:
      - "main"

env:
  HANGAR_API_KEY: ${{ secrets.HANGAR_API_KEY }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
      - name: Build
        shell: "bash"
        run: gradle -Pversion=${{ github.event.release.tag_name || github.ref_name }} -Dmaven.repo.local=${{github.workspace}}/localM2Repository build publishPluginPublicationToHangar
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            build/libs/*.jar